# Generated by Django 5.2.5 on 2025-09-21 14:15

import ckeditor_uploader.fields
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import tcikets.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('report', models.TextField(verbose_name='Intervention Report')),
                ('intervention_date', models.DateField(auto_now_add=True, verbose_name='Intervention Date')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Start Time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='End Time')),
                ('transport_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Transport Cost')),
                ('additional_costs', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Additional Costs')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Cost')),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Hours Worked')),
                ('travel_time', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Travel Time (hours)')),
                ('materials_used', models.TextField(blank=True, null=True, verbose_name='Materials Used')),
                ('equipment_used', models.TextField(blank=True, null=True, verbose_name='Equipment Used')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20, verbose_name='Intervention Status')),
                ('customer_signature', models.TextField(blank=True, null=True, verbose_name='Customer Signature')),
                ('customer_feedback', models.TextField(blank=True, null=True, verbose_name='Customer Feedback')),
                ('customer_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Customer Rating')),
                ('technician_notes', models.TextField(blank=True, null=True, verbose_name='Technician Notes')),
                ('internal_notes', models.TextField(blank=True, null=True, verbose_name='Internal Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Intervention',
                'verbose_name_plural': 'Interventions',
                'ordering': ['-intervention_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tag de procédure',
                'verbose_name_plural': 'Tags de procédure',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+242999999999'. Up to 15 digits allowed.", regex='^\\+?242?\\d{9,15}$')])),
                ('userType', models.CharField(choices=[('admin', 'Admin'), ('technician', 'Technician'), ('client', 'Client')], default='client', max_length=20)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=tcikets.models.user_avatar_path)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'swappable': 'AUTH_USER_MODEL',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+242999999999'. Up to 15 digits allowed.", regex='^\\+?242?\\d{9,15}$')])),
                ('company', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterventionExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expense_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='expense_receipts/')),
                ('date_incurred', models.DateField()),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='tcikets.intervention')),
            ],
        ),
        migrations.CreateModel(
            name='InterventionImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='intervention_images/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tcikets.intervention')),
            ],
        ),
        migrations.CreateModel(
            name='InterventionMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('serial_number', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='tcikets.intervention')),
            ],
        ),
        migrations.CreateModel(
            name='PendingConfirmation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcikets.intervention')),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField()),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('category', models.CharField(choices=[('general', 'Général'), ('hardware', 'Hardware'), ('software', 'Software'), ('network', 'Réseau'), ('security', 'Sécurité'), ('maintenance', 'Maintenance')], db_index=True, default='general', max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé')], db_index=True, default='intermediate', max_length=20)),
                ('estimated_time', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views', models.PositiveIntegerField(db_index=True, default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('bookmarks', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé')], db_index=True, default='draft', max_length=20)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description', max_length=160)),
                ('featured', models.BooleanField(db_index=True, default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_procedures', to=settings.AUTH_USER_MODEL)),
                ('related_procedures', models.ManyToManyField(blank=True, to='tcikets.procedure')),
                ('tags', models.ManyToManyField(blank=True, related_name='procedures', to='tcikets.proceduretag')),
            ],
            options={
                'verbose_name': 'Procédure',
                'verbose_name_plural': 'Procédures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=tcikets.models.procedure_attachment_path)),
                ('name', models.CharField(max_length=200)),
                ('file_type', models.CharField(max_length=50)),
                ('file_size', models.CharField(max_length=20)),
                ('attachment_type', models.CharField(choices=[('document', 'Document'), ('video', 'Vidéo'), ('archive', 'Archive'), ('other', 'Autre')], default='other', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tcikets.procedure')),
            ],
            options={
                'verbose_name': 'Pièce jointe de procédure',
                'verbose_name_plural': 'Pièces jointes de procédure',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=tcikets.models.procedure_image_path)),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('alt_text', models.CharField(blank=True, max_length=200, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tcikets.procedure')),
            ],
            options={
                'verbose_name': 'Image de procédure',
                'verbose_name_plural': 'Images de procédure',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('change_summary', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='tcikets.procedure')),
            ],
            options={
                'verbose_name': 'Version de procédure',
                'verbose_name_plural': 'Versions de procédure',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('specialty', models.CharField(choices=[('hardware', 'Matériel'), ('software', 'Logiciel'), ('network', 'Réseau'), ('security', 'Sécurité')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+242999999999'. Up to 15 digits allowed.", regex='^\\+?242?\\d{9,15}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technician_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='intervention',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to='tcikets.technician'),
        ),
        migrations.CreateModel(
            name='ClientRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='tcikets.client')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to='tcikets.technician')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicianRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to='tcikets.client')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='tcikets.technician')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('material_name', models.CharField(blank=True, max_length=100, null=True)),
                ('problem_start_date', models.DateTimeField(blank=True, null=True)),
                ('problem_type', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('in_progress', 'En cours'), ('resolved', 'Resolu'), ('closed', 'Fermee')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='ticket_attachments/')),
                ('tags', models.CharField(blank=True, max_length=100, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tcikets.client')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tcikets.technician')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tcikets.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='chat_images/%Y/%m/%d/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('whatsapp_status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyé'), ('delivered', 'Livré'), ('failed', 'Échec'), ('read', 'Lu')], default='pending', max_length=10)),
                ('whatsapp_sid', models.CharField(blank=True, max_length=50, null=True)),
                ('is_whatsapp', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tcikets.ticket')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='intervention',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='tcikets.ticket'),
        ),
        migrations.CreateModel(
            name='TicketImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ticket_images/')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tcikets.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('view', 'Vue'), ('like', 'Like'), ('bookmark', 'Bookmark'), ('share', 'Partage')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcikets.procedure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interaction avec procédure',
                'verbose_name_plural': 'Interactions avec procédures',
                'indexes': [models.Index(fields=['procedure', 'interaction_type'], name='tcikets_pro_procedu_b73e70_idx'), models.Index(fields=['user', 'interaction_type'], name='tcikets_pro_user_id_2dab01_idx'), models.Index(fields=['-created_at'], name='tcikets_pro_created_f328ac_idx')],
                'unique_together': {('user', 'procedure', 'interaction_type')},
            },
        ),
        migrations.AddIndex(
            model_name='procedure',
            index=models.Index(fields=['status', 'is_active', '-created_at'], name='tcikets_pro_status_202d69_idx'),
        ),
        migrations.AddIndex(
            model_name='procedure',
            index=models.Index(fields=['category', 'difficulty'], name='tcikets_pro_categor_0beb29_idx'),
        ),
        migrations.AddIndex(
            model_name='procedure',
            index=models.Index(fields=['-views'], name='tcikets_pro_views_2b9699_idx'),
        ),
        migrations.AddIndex(
            model_name='procedure',
            index=models.Index(fields=['featured', '-created_at'], name='tcikets_pro_feature_56153b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='procedureversion',
            unique_together={('procedure', 'version_number')},
        ),
        migrations.AlterUniqueTogether(
            name='clientrating',
            unique_together={('client', 'technician')},
        ),
        migrations.AlterUniqueTogether(
            name='technicianrating',
            unique_together={('technician', 'client')},
        ),
    ]
