# Generated by Django 5.2.5 on 2025-09-23 10:31

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcikets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
